name: README Repos List
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: DenverCoderOne/readme-repos-list@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:MrSebi06"
          max: 10
